# Generated by Django 5.2.5 on 2025-08-19 11:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesplit',
            name='contribution',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='groupexpense',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupexpense',
            name='participants',
            field=models.ManyToManyField(related_name='participated_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupexpense',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal Split'), ('percentage', 'Split by Percentage'), ('amount', 'Split by Amount')], default='equal', max_length=10),
        ),
        migrations.CreateModel(
            name='GroupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Group Created'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('expense_added', 'Expense Added'), ('expense_edited', 'Expense Edited'), ('expense_deleted', 'Expense Deleted')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='mainApp.group')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
