# Generated by Django 5.2.3 on 2025-08-19 13:08

import uuid
from django.db import migrations


def generate_unique_invite_tokens(apps, schema_editor):
    """Generate unique invite tokens for existing groups"""
    Group = apps.get_model('mainApp', 'Group')
    for group in Group.objects.all():
        group.invite_token = uuid.uuid4()
        group.save()


def reverse_generate_unique_invite_tokens(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_group_invite_token'),
    ]

    operations = [
        migrations.RunPython(generate_unique_invite_tokens, reverse_generate_unique_invite_tokens),
    ]
