# Generated by Django 5.2.3 on 2025-08-19 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20250819_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
