# Generated by Django 5.2.5 on 2025-08-25 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Expense Created'), ('edited', 'Expense Edited'), ('amount_changed', 'Amount Changed'), ('participants_changed', 'Participants Changed'), ('split_type_changed', 'Split Type Changed'), ('description_changed', 'Description Changed'), ('title_changed', 'Title Changed'), ('category_changed', 'Category Changed')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='mainApp.groupexpense')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
