# Generated by Django 5.2.5 on 2025-08-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_chatmessage_image_chatmessage_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, help_text='Text content for text messages'),
        ),
    ]
