# Generated by Django 5.2.3 on 2025-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouphistory',
            name='action',
            field=models.CharField(choices=[('created', 'Group Created'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('expense_added', 'Expense Added'), ('expense_edited', 'Expense Edited'), ('expense_deleted', 'Expense Deleted'), ('invite_link_regenerated', 'Invite Link Regenerated')], max_length=25),
        ),
    ]
