# Generated by Django 5.2.3 on 2025-09-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_alter_grouphistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensehistory',
            name='action',
            field=models.CharField(choices=[('created', 'Expense Created'), ('edited', 'Expense Edited'), ('amount_changed', 'Amount Changed'), ('participants_changed', 'Participants Changed'), ('split_type_changed', 'Split Type Changed'), ('description_changed', 'Description Changed'), ('title_changed', 'Title Changed'), ('category_changed', 'Category Changed'), ('contributions_changed', 'Contributions Changed'), ('split_amounts_changed', 'Split Amounts Changed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('expense_added', 'Expense Added'), ('expense_edited', 'Expense Edited'), ('expense_updated', 'Expense Updated'), ('expense_deleted', 'Expense Deleted'), ('settle_request', 'Settlement Request'), ('settle_approved', 'Settlement Approved'), ('settle_rejected', 'Settlement Rejected'), ('group_invite', 'Group Invitation'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left')], max_length=20),
        ),
    ]
