# Generated by Django 5.2.3 on 2025-09-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_alter_expensehistory_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensehistory',
            name='action',
            field=models.CharField(choices=[('created', 'Expense Created'), ('edited', 'Expense Edited'), ('expense_updated', 'Expense Updated'), ('amount_changed', 'Amount Changed'), ('participants_changed', 'Participants Changed'), ('split_type_changed', 'Split Type Changed'), ('description_changed', 'Description Changed'), ('title_changed', 'Title Changed'), ('category_changed', 'Category Changed'), ('contributions_changed', 'Contributions Changed'), ('split_amounts_changed', 'Split Amounts Changed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='grouphistory',
            name='action',
            field=models.CharField(choices=[('created', 'Group Created'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('expense_added', 'Expense Added'), ('expense_deleted', 'Expense Deleted'), ('invite_link_regenerated', 'Invite Link Regenerated')], max_length=25),
        ),
    ]
