# Generated by Django 5.2.3 on 2025-09-04 19:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_alter_expensehistory_action_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('expense_added', 'Expense Added'), ('expense_edited', 'Expense Edited'), ('expense_updated', 'Expense Updated'), ('expense_deleted', 'Expense Deleted'), ('settle_request', 'Settlement Request'), ('settle_request_sent', 'Settlement Request Sent'), ('settle_approved', 'Settlement Approved'), ('settle_approved_confirmation', 'Settlement Approved Confirmation'), ('settle_rejected', 'Settlement Rejected'), ('settle_rejected_confirmation', 'Settlement Rejected Confirmation'), ('payment_reminder', 'Payment Reminder'), ('group_invite', 'Group Invitation'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left')], max_length=40),
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reminder_type', models.CharField(choices=[('email', 'Email Reminder'), ('notification', 'In-App Notification')], max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reminders', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='mainApp.group')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
