# Generated by Django 5.2.3 on 2025-09-05 05:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_notification_notification_type_paymentreminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouphistory',
            name='action',
            field=models.CharField(choices=[('created', 'Group Created'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('member_left', 'Member Left'), ('admin_transferred', 'Admin Transferred'), ('deletion_requested', 'Deletion Requested'), ('group_deleted', 'Group Deleted'), ('expense_added', 'Expense Added'), ('expense_deleted', 'Expense Deleted'), ('invite_link_regenerated', 'Invite Link Regenerated')], max_length=25),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('expense_added', 'Expense Added'), ('expense_edited', 'Expense Edited'), ('expense_updated', 'Expense Updated'), ('expense_deleted', 'Expense Deleted'), ('settle_request', 'Settlement Request'), ('settle_request_sent', 'Settlement Request Sent'), ('settle_approved', 'Settlement Approved'), ('settle_approved_confirmation', 'Settlement Approved Confirmation'), ('settle_rejected', 'Settlement Rejected'), ('settle_rejected_confirmation', 'Settlement Rejected Confirmation'), ('payment_reminder', 'Payment Reminder'), ('group_invite', 'Group Invitation'), ('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('admin_transferred', 'Admin Transferred'), ('group_deletion_request', 'Group Deletion Request'), ('group_deletion_rejected', 'Group Deletion Rejected'), ('group_deleted', 'Group Deleted')], max_length=40),
        ),
        migrations.CreateModel(
            name='GroupDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='mainApp.group')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('group', 'status')},
            },
        ),
        migrations.CreateModel(
            name='GroupDeletionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('pending', 'Pending'), ('agree', 'Agree'), ('disagree', 'Disagree')], default='pending', max_length=10)),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deletion_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='mainApp.groupdeletionrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['voted_at'],
                'unique_together': {('deletion_request', 'user')},
            },
        ),
    ]
