# Generated by Django 5.2.5 on 2025-09-05 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_alter_grouphistory_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='group_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.groupexpense'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='personal_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.personalexpense'),
        ),
    ]
